#!/bin/bash 
#
#
# This script will update casacore-data and upload it to the KERN ppa
#

set -e 
set -v

export DEBEMAIL=packaging@kernsuite.info
export DEBFULLNAME='KERN packaging (KERN-6+ key)'

DIST=xenial
gbp import-orig --uscan --no-interactive
gbp dch -D ${DIST}
VERSION_RAW=`cat debian/changelog | grep casacore-data | head -n 1 | awk '{print $2}'`
VERSION=${VERSION_RAW:1:-1}
git commit debian/changelog -m "Release '${VERSION}' for ${DIST}"
gbp buildpackage --git-tag
gbp buildpackage -S -sa
dput -f ppa:kernsuite/kern-3 ../casacore-data_${VERSION}_source.changes

DIST=bionic
dch -D ${DIST} --force-distribution -U  "build for bionic"
VERSION_RAW=`cat debian/changelog | grep casacore-data | head -n 1 | awk '{print $2}'` 
VERSION=${VERSION_RAW:1:-1}
git commit debian/changelog -m "Release '${VERSION}' for ${DIST}"
gbp buildpackage --git-tag
#git push --all --follow-tags
gbp buildpackage -S -sa
dput -f ppa:kernsuite/kern-4 ../casacore-data_${VERSION}_source.changes
dput -f ppa:kernsuite/kern-5 ../casacore-data_${VERSION}_source.changes
dput -f ppa:kernsuite/kern-6 ../casacore-data_${VERSION}_source.changes
dput -f ppa:kernsuite/kern-dev ../casacore-data_${VERSION}_source.changes

DIST=focal
dch -D ${DIST} --force-distribution -U  "build for ${DIST}"
VERSION_RAW=`cat debian/changelog | grep casacore-data | head -n 1 | awk '{print $2}'` 
VERSION=${VERSION_RAW:1:-1}
git commit debian/changelog -m "Release '${VERSION}' for ${DIST}"
gbp buildpackage --git-tag
#git push --all --follow-tags
gbp buildpackage -S -sa
dput -f ppa:kernsuite/kern-7 ../casacore-data_${VERSION}_source.changes
dput -f ppa:kernsuite/kern-8 ../casacore-data_${VERSION}_source.changes
dput -f ppa:kernsuite/kern-dev ../casacore-data_${VERSION}_source.changes

DIST=jammy
dch -D ${DIST} --force-distribution -U  "build for ${DIST}"
VERSION_RAW=`cat debian/changelog | grep casacore-data | head -n 1 | awk '{print $2}'`
VERSION=${VERSION_RAW:1:-1}
git commit debian/changelog -m "Release '${VERSION}' for ${DIST}"
gbp buildpackage --git-tag
#git push --all --follow-tags
gbp buildpackage -S -sa
dput -f ppa:kernsuite/kern-9 ../casacore-data_${VERSION}_source.changes
dput -f ppa:kernsuite/kern-dev ../casacore-data_${VERSION}_source.changes

DIST=noble
dch -D ${DIST} --force-distribution -U  "build for ${DIST}"
VERSION_RAW=cat debian/changelog | grep casacore-data | head -n 1 | awk '{print $2}'
VERSION=${VERSION_RAW:1:-1}
git commit debian/changelog -m "Release '${VERSION}' for ${DIST}"
gbp buildpackage --git-tag
#git push --all --follow-tags
gbp buildpackage -S -sa
dput -f ppa:kernsuite/kern-10 ../casacore-data_${VERSION}_source.changes
dput -f ppa:kernsuite/kern-dev ../casacore-data_${VERSION}_source.changes
