#!/bin/bash 
#
#
# This script will update casacore-data and upload it to the KERN ppa
#

VERSION_RAW=`cat debian/changelog | grep casacore-data | head -n 1 | awk '{print $2}'`
VERSION=${VERSION_RAW:1:-1}

git commit debian/changelog -m "Release '${VERSION}'"
gbp buildpackage --git-tag
git push --all
git push --tags
gbp buildpackage -S -sa
dput -f ppa:kernsuite/kern-dev ../casacore-data_${VERSION}_source.changes
dput -f ppa:kernsuite/kern-3 ../casacore-data_${VERSION}_source.changes


