#!/bin/bash 
#
#
# This script will update casacore-data and upload it to the KERN ppa
#

set -e 
set -v

gbp import-orig --uscan
GIT_AUTHOR_EMAIL=$DEBEMAIL GIT_AUTHOR_NAME=$DEBFULLNAME gbp dch -D xenial

echo "ok cool. now edit debian/changelog and update the signature"

